apiVersion: v1
kind: ResourceQuota
metadata:
   name: flashbladequota
spec:
  hard:
    pure-file.storageclass.storage.k8s.io/persistentvolumeclaims: "100"
    pure-file.storageclass.storage.k8s.io/requests.storage: "100Ti"
